### ISSUE TITLE
intuitlib.version.__version__ in master is 1.2.2 but the latest version on pypi is 1.2.3

### ISSUE THREAD

**Issue by dreid** [intuit/oauth-pythonclient#12]
The 1.2.3 tag *also* has `intuitlib.version.__version__` set to 1.2.2. At this point it's pretty hard to tell what source produced the sdist or the wheel on pypi.

Y'all might want to consider adopting some tooling (such as [incremental](https://github.com/twisted/incremental) for managing version numbers automatically and integrating that into whatever release automation you have.

**Comment by fjolin-intuit** [comment]
Thanks dreid!
