### ISSUE TITLE
Refresh token issue

### ISSUE THREAD

**Issue by shaikhmasud147** [intuit/oauth-pythonclient#20]
refresh token is expiring within 24hrs. So please let me know
How we can generate new refresh token?

i am tried to below code but is it not working.
new_token = auth_client.refresh

**Comment by nimisha84** [comment]
There isn't a way to generate new refresh token. You will need to do oauth and make sure you handle token expiration as per below recommendation for future.
https://help.developer.intuit.com/s/article/Validity-of-Refresh-Token
