### ISSUE TITLE
SDK affected by: Intuit changes to identity signature keys

### ISSUE THREAD

**Issue by dantebarba** [intuit/oauth-pythonclient#43]
This is mostly a question / concern

There is no information if the Python SDK is affected by the changes to identity signature that are going to be introduced on March 1st, 2024. 

1. Is this SDK affected by the change? 
2. Will a new version be released addressing this issue?
3. In case it's not affected, from which version should the SDK work correctly?

More info: https://app.dp.intuit.com/e/es?s=2332625&e=186&elqTrackId=efd74c1a1b7a40299e524d6e5aa03bea&elq=3a05f012fe5f4115aa4a636e773429d0&elqaid=78&elqat=1

**Comment by shweta-intuitdev** [comment]
Hello! This client library will continue to work as-is after the OpenID changes go live. No need to make any changes.

**Comment by dantebarba** [comment]
Thanks!
