### ISSUE TITLE
Intuit blocking default (python) user-agent from requests library

### ISSUE THREAD

**Issue by mrhattyhat** [intuit/oauth-pythonclient#6]
Today my integrations with QB Payments API stopped working, failing with a 404 trying to get the discovery doc as part of AuthClient initialization (client.py line 56).  Debugging it, I captured the discovery URL and tried to request it directly in Chrome, which worked.  Then I tried a requests.get request on it in a Python shell and it came back 404.  So I set the User-Agent header to Mozilla/5.0 and tried requests.get again and it worked.  So apparently something changed today on the Intuit side that's causing requests to fail if not from an "approved" User-Agent (or something).

I can't see from your client code any way to set the User-Agent header prior to making the discovery doc request.  Any suggestions?  Maybe some way to lazy-load the discovery doc, or pass in the request headers.  Or since AuthClient is based on requests.Session, maybe just make it default to a "real" User-Agent.

**Comment by mrhattyhat** [comment]
I solved the problem for myself locally by creating a sub-class of AuthClient and overloading __init__, setting 

`self.headers['User-Agent'] = 'Mozilla/5.0' `

before get_discovery_doc is called.  Seems to be working again.  Still, might be nice to offer some kind of solution in the client itself rather than having to overload it.

**Comment by diana-derose** [comment]
Hi @mrhattyhat  - Thanks for letting us know, we'll take a look at this and apply a fix asap.

**Comment by hlu2** [comment]
The above issue has been fixed.
