### ISSUE TITLE
HTTP status 415 in production

### ISSUE THREAD

**Issue by mdagosta** [intuit/oauth-pythonclient#8]
I am running into a problem with AuthClient.get_user_info(). I'm able to get the bearer token successfully, and in the sandbox get_user_info() is working. However, in production I am getting HTTP status 415. The error message is empty string.

What can I do about this? From reading years old posts on developer.intuit.com I'm wondering if there's a wrong setting on my account or something like this. But with no error message I'm guessing...

Reading through the docs here it looks like the auth_client is set up correctly to me... 
https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/openid-connect#obtaining-user-profile-information

Works in sandbox. Doesn't work in production. What should I do next? 

Big thanks in advance!

**Comment by hlu2** [comment]
It looks like a configuration issue to me. Check your header field for Content-Type, make sure it is Content-Type: application/json.

**Comment by hlu2** [comment]
It is a bug in the SDK.

I think the problem is the session. 

The 
auth_client.get_bearer_token(auth_code, realm_id=realm_id) 
somehow update the Session header with "Content type: application/x-www-form-urlencoded" and it is added to the header when making the API request get_user_info(), thus resulting a 415. 

I will fix the SDK and release it soon.

**Comment by ladytrontech** [comment]
Thanks Hao. I saw your update on the Intuit support site. For future reference, should we be posting these issues here or on the Intuit Dev Support site?

**Comment by mdagosta** [comment]
I saw your commits so I updated to your latest; now it works in production! Awesome, thanks Hao! You fixed it.
