### ISSUE TITLE
pip installed library missing __init__.py file

### ISSUE THREAD

**Issue by jacobg** [intuit/oauth-pythonclient#9]
When installing via pip, the `__init__.py` file is missing. See screenshot below.

And just to make sure it's not a configuration issue on my machine, I downloaded the wheel directly, unzipped it, and it's also missing the `__init__.py` file:
https://files.pythonhosted.org/packages/73/14/537d33a2dc19469743dc75eee317a9cf439497b7446928f345df086c5316/intuit_oauth-1.2.1-py2-none-any.whl

<img width="222" alt="screen shot 2019-03-05 at 2 24 07 pm" src="https://user-images.githubusercontent.com/736985/53831312-8bfd1d00-3f52-11e9-83ca-f57da8ac4f27.png">

**Comment by hlu2** [comment]
It should be there. Can you check your folders? Maybe the file is hidden.

**Comment by jacobg** [comment]
Nope. It's even missing from the RECORD file in the wheel:
```
intuit_oauth-1.2.1-py2.7-nspkg.pth,sha256=6aIBmizpbr5QJexcjrXZXQE4soGnRkmjRGH05ZSoFv8,554
intuitlib/client.py,sha256=5UhX_i0KLIa9dLJDTijNLT0ViVMcLaDv89hUx8NBdMI,7200
intuitlib/config.py,sha256=21fXhbgyHZRzpmOGc-lTYXxaXcMdoSISYhWcqyJmdmo,1434
intuitlib/enums.py,sha256=6ZOWG9P7KRB2S6Y7mHH8PrGBdtpolwCoyNkhL-DyWsA,1348
intuitlib/exceptions.py,sha256=HxyG7t3FRcFQbMwYwqqtAMLmIhIelTeKP5ckJFspUpo,1355
intuitlib/migration.py,sha256=jCIVVLznzhS36jXFct8xYfDMQaLVPdsXmSGH_BUr66Q,2063
intuitlib/utils.py,sha256=3yZ78i4Q96Hqbw6HJKpMvkTR_6VOD98tyUMKn3p9GuU,6847
intuitlib/version.py,sha256=CVM6WTRviRCVoMxvEwlJir6A6gizEWL4r4XgAtO9vUA,608
intuit_oauth-1.2.1.dist-info/LICENSE,sha256=DKdywWkIisiWao0CDRFXTpW-VCj0Dxp2ihktFD5a1Iw,11342
intuit_oauth-1.2.1.dist-info/METADATA,sha256=AoZmpyjsr0ULNm9U1CNBCvGYHAgD0KMs9GGz5VoMgow,2779
intuit_oauth-1.2.1.dist-info/WHEEL,sha256=_eaHuBxOHdDlLnwQU30U16Q6vfvhsEhxIYEpcPcf8n0,92
intuit_oauth-1.2.1.dist-info/namespace_packages.txt,sha256=Aq1wmGSlAfMvYq_levlg2_V5ZDKQ08ZuJFdkQ96bbTw,10
intuit_oauth-1.2.1.dist-info/top_level.txt,sha256=Aq1wmGSlAfMvYq_levlg2_V5ZDKQ08ZuJFdkQ96bbTw,10
intuit_oauth-1.2.1.dist-info/RECORD,,
```

**Comment by jacobg** [comment]
I think the issue may be that intuitlib is published as a namespace package, so the init.py is not included. But that is not compatible with python 2.7 which I am using. Can you please adjust the setup configuration to include init.py for compatibility?

**Comment by hlu2** [comment]
When I create the wheel, it clearly says:
copying intuitlib/__init__.py -> intuit-oauth-1.2.2/intuitlib
I don't think there is anything wrong with the setup. What is your OS system?

**Comment by jacobg** [comment]
I'm on MacOS.

When you extract either the published wheel (as a zip file) or gzip at:

https://files.pythonhosted.org/packages/73/14/537d33a2dc19469743dc75eee317a9cf439497b7446928f345df086c5316/intuit_oauth-1.2.1-py2-none-any.whl

https://files.pythonhosted.org/packages/ba/e5/eec47c573f5210f7793be4a980abc56c617844dd37e22344cd16d752a81e/intuit-oauth-1.2.2.tar.gz

Do you see the `__init__.py` file in either one?

I cloned the the git repo also, and ran `python setup.py sdist bdist_wheel`, and it's also missing in the local build. The stdout has this line:
```
Skipping installation of build/bdist.macosx-10.13-x86_64/wheel/intuitlib/__init__.py (namespace package)
```

**Comment by hlu2** [comment]
I just made a new release to fix a bug in the SDK. mind give it another try and see if the error resolved?
make sure you run 
`pip uninstall` first

**Comment by jacobg** [comment]
Still missing in 1.2.2. Did you check the published whl and gz files?

**Comment by jacobg** [comment]
So it is in the gz file, but it's missing in the whl.

**Comment by jacobg** [comment]
It seems there's a known issue with namespace packages and wheels:
https://github.com/pypa/setuptools/issues/1097

I've never seen this issue before though, I presume because other 3rd party libraries I'm using don't use pkg_resources-style namespace packages.
